version: 2

project_name: ingress-nginx
release:
  disable: true
builds:
  - id: ingress-nginx
    goos:
    - darwin
    - linux
    - windows
    goarch:
    - arm64
    - amd64
    env:
    - CGO_ENABLED=0
    - GO111MODULE=on
    main: cmd/plugin/main.go
    binary: kubectl-ingress-nginx
    ldflags: |
      -s -w
      -X k8s.io/ingress-nginx/version.COMMIT={{ .Commit }}
      -X k8s.io/ingress-nginx/version.RELEASE=controller-{{ .Tag }}
archives:
  - id: ingress-nginx
    ids:
    - ingress-nginx
    name_template: "kubectl-{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats:
    - tar.gz
checksum:
  name_template: "kubectl-{{ .ProjectName }}_checksums.txt"

krews:
  - skip_upload: true
    homepage: "https://kubernetes.github.io/ingress-nginx/kubectl-plugin/"
    description: "The official kubectl plugin for ingress-nginx."
    short_description: "Interact with ingress-nginx"
    url_template: "http://github.com/alexintech/ingress-nginx/releases/download/controller-{{ .Tag }}/{{ .ArtifactName }}"
