options:
  # Ignore Prow provided substitutions.
  substitution_option: ALLOW_LOOSE
steps:
  - name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20250116-2a05ea7e3d
    env:
      - REGISTRY=us-central1-docker.pkg.dev/k8s-staging-images/ingress-nginx
      - REPO_INFO=https://github.com/kubernetes/ingress-nginx
      - COMMIT_SHA=${_PULL_BASE_SHA}
      - BUILD_ID=${BUILD_ID}
    entrypoint: bash
    args:
      - -c
      - gcloud auth configure-docker && make release
