options:
  # Ignore Prow provided substitutions.
  substitution_option: ALLOW_LOOSE
steps:
- name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20251211-4c812d4cd8
  env:
  - REPO_INFO=https://github.com/kubernetes/ingress-nginx
  - COMMIT_SHA=${_PULL_BASE_SHA}
  - BUILD_ID=${BUILD_ID}
  entrypoint: make
  args:
  - release
