apiVersion: v1
kind: Pod
metadata:
  name: simple
spec:
  containers:
  - image: gcr.io/google_containers/haproxy:0.2
    imagePullPolicy: Always
    name: haproxy
    command:
    - /usr/sbin/haproxy
    args:
    - -db
    - -f
    - /etc/haproxy/haproxy.cfg
    ports:
    - containerPort: 80
