options:
  # Ignore Prow provided substitutions.
  substitution_option: ALLOW_LOOSE
steps:
# Show version.
- name: $_DOCKER
  args:
  - version
# Show info.
- name: $_DOCKER
  args:
  - info
# List builders.
- name: $_DOCKER
  args:
  - buildx
  - ls
# Create builder.
- name: $_DOCKER
  args:
  - buildx
  - create
  - --platform
  - linux/amd64,linux/arm,linux/arm64
  - --bootstrap
  - --use
# List builders.
- name: $_DOCKER
  args:
  - buildx
  - ls
# Inspect builder.
- name: $_DOCKER
  args:
  - buildx
  - inspect
