options:
  # Increase machine type for multi-arch builds.
  machineType: E2_HIGHCPU_32
  # Ignore Prow provided substitutions.
  substitution_option: ALLOW_LOOSE
steps:
- name: gcr.io/cloud-builders/docker
  dir: images/nginx
  entrypoint: make
  args:
  - push
timeout: 7200s
