timeout: 10800s
options:
  substitution_option: ALLOW_LOOSE
  # job builds a multi-arch docker image for amd64,arm,arm64 and s390x.
  machineType: N1_HIGHCPU_32
steps:
  - name: 'gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20211118-2f2d816b90'
    entrypoint: bash
    env:
      - DOCKER_CLI_EXPERIMENTAL=enabled
      - BASE_REF=$_PULL_BASE_REF
      - TAG=$_PULL_BASE_SHA
      - REGISTRY=gcr.io/k8s-staging-ingress-nginx
      - HOME=/root
    args:
    - -c
    - |
      gcloud auth configure-docker \
      && cd images/nginx && make push
substitutions:
  _GIT_TAG: "12345"
  _PULL_BASE_REF: "master"
  _PULL_BASE_SHA: '12345'
