options:
  # Ignore Prow provided substitutions.
  substitution_option: ALLOW_LOOSE
steps:
# Show version.
- name: gcr.io/cloud-builders/docker
  args:
  - version
# Show info.
- name: gcr.io/cloud-builders/docker
  args:
  - info
# Show version.
- name: gcr.io/cloud-builders/docker
  args:
  - buildx
  - version
# List builders.
- name: gcr.io/cloud-builders/docker
  args:
  - buildx
  - ls
  - --no-trunc
