// Copyright 2022 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: pkg/apis/ingress/ingress.proto

package ingress

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BackendName is the backend requesting the operation. All requests should contain
// the backend name to be validated by control plane
type BackendName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name of the backend that posted the message
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// namespace of the backend that posted the message
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *BackendName) Reset() {
	*x = BackendName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackendName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendName) ProtoMessage() {}

func (x *BackendName) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendName.ProtoReflect.Descriptor instead.
func (*BackendName) Descriptor() ([]byte, []int) {
	return file_pkg_apis_ingress_ingress_proto_rawDescGZIP(), []int{0}
}

func (x *BackendName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackendName) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// Configurations contains the configuration sent to backend
type Configurations struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Op:
	//	*Configurations_FullconfigOp
	Op isConfigurations_Op `protobuf_oneof:"op"`
}

func (x *Configurations) Reset() {
	*x = Configurations{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Configurations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configurations) ProtoMessage() {}

func (x *Configurations) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configurations.ProtoReflect.Descriptor instead.
func (*Configurations) Descriptor() ([]byte, []int) {
	return file_pkg_apis_ingress_ingress_proto_rawDescGZIP(), []int{1}
}

func (m *Configurations) GetOp() isConfigurations_Op {
	if m != nil {
		return m.Op
	}
	return nil
}

func (x *Configurations) GetFullconfigOp() *Configurations_FullConfiguration {
	if x, ok := x.GetOp().(*Configurations_FullconfigOp); ok {
		return x.FullconfigOp
	}
	return nil
}

type isConfigurations_Op interface {
	isConfigurations_Op()
}

type Configurations_FullconfigOp struct {
	FullconfigOp *Configurations_FullConfiguration `protobuf:"bytes,2,opt,name=fullconfig_op,json=fullconfigOp,proto3,oneof"`
}

func (*Configurations_FullconfigOp) isConfigurations_Op() {}

// EventMessage contains the message to be turned into a Kubernetes event
type EventMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Backend   *BackendName `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty"`
	Eventtype string       `protobuf:"bytes,2,opt,name=eventtype,proto3" json:"eventtype,omitempty"`
	Reason    string       `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message   string       `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *EventMessage) Reset() {
	*x = EventMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMessage) ProtoMessage() {}

func (x *EventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMessage.ProtoReflect.Descriptor instead.
func (*EventMessage) Descriptor() ([]byte, []int) {
	return file_pkg_apis_ingress_ingress_proto_rawDescGZIP(), []int{2}
}

func (x *EventMessage) GetBackend() *BackendName {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *EventMessage) GetEventtype() string {
	if x != nil {
		return x.Eventtype
	}
	return ""
}

func (x *EventMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EventMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_apis_ingress_ingress_proto_rawDescGZIP(), []int{3}
}

// FullConfiguration messages contains the whole NGINX configuration and it is up
// to the backend to decide if this needs a reload or it is dynamic
type Configurations_FullConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// TODO: turn this into "any" or generate proper protobuf tags
	Configuration []byte `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
}

func (x *Configurations_FullConfiguration) Reset() {
	*x = Configurations_FullConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Configurations_FullConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configurations_FullConfiguration) ProtoMessage() {}

func (x *Configurations_FullConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_ingress_ingress_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configurations_FullConfiguration.ProtoReflect.Descriptor instead.
func (*Configurations_FullConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_apis_ingress_ingress_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Configurations_FullConfiguration) GetConfiguration() []byte {
	if x != nil {
		return x.Configuration
	}
	return nil
}

var File_pkg_apis_ingress_ingress_proto protoreflect.FileDescriptor

var file_pkg_apis_ingress_ingress_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x69, 0x6e, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x2f, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x09, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x76, 0x31, 0x22, 0x3f, 0x0a, 0x0b, 0x42,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0xa5, 0x01, 0x0a,
	0x0e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x52, 0x0a, 0x0d, 0x66, 0x75, 0x6c, 0x6c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x6f, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x46, 0x75, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0c, 0x66, 0x75, 0x6c, 0x6c, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x4f, 0x70, 0x1a, 0x39, 0x0a, 0x11, 0x46, 0x75, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x04,
	0x0a, 0x02, 0x6f, 0x70, 0x22, 0x90, 0x01, 0x0a, 0x0c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x76, 0x31, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x07,
	0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x32, 0xa7, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x4c, 0x0a, 0x13, 0x57, 0x61, 0x74, 0x63, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x2e, 0x69, 0x6e, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4e, 0x61, 0x6d,
	0x65, 0x1a, 0x19, 0x2e, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x76, 0x31, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x00, 0x30, 0x01,
	0x12, 0x48, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x2e, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x76,
	0x31, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x19, 0x2e,
	0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x00, 0x32, 0x4d, 0x0a, 0x0c, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x2e, 0x69, 0x6e, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x1a, 0x10, 0x2e, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x76, 0x31, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x28, 0x01, 0x42, 0x27, 0x5a, 0x25, 0x6b, 0x38, 0x73,
	0x2e, 0x69, 0x6f, 0x2f, 0x69, 0x6e, 0x67, 0x72, 0x65, 0x73, 0x73, 0x2d, 0x6e, 0x67, 0x69, 0x6e,
	0x78, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x69, 0x6e, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_apis_ingress_ingress_proto_rawDescOnce sync.Once
	file_pkg_apis_ingress_ingress_proto_rawDescData = file_pkg_apis_ingress_ingress_proto_rawDesc
)

func file_pkg_apis_ingress_ingress_proto_rawDescGZIP() []byte {
	file_pkg_apis_ingress_ingress_proto_rawDescOnce.Do(func() {
		file_pkg_apis_ingress_ingress_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_apis_ingress_ingress_proto_rawDescData)
	})
	return file_pkg_apis_ingress_ingress_proto_rawDescData
}

var file_pkg_apis_ingress_ingress_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_apis_ingress_ingress_proto_goTypes = []interface{}{
	(*BackendName)(nil),                      // 0: ingressv1.BackendName
	(*Configurations)(nil),                   // 1: ingressv1.Configurations
	(*EventMessage)(nil),                     // 2: ingressv1.EventMessage
	(*Empty)(nil),                            // 3: ingressv1.Empty
	(*Configurations_FullConfiguration)(nil), // 4: ingressv1.Configurations.FullConfiguration
}
var file_pkg_apis_ingress_ingress_proto_depIdxs = []int32{
	4, // 0: ingressv1.Configurations.fullconfig_op:type_name -> ingressv1.Configurations.FullConfiguration
	0, // 1: ingressv1.EventMessage.backend:type_name -> ingressv1.BackendName
	0, // 2: ingressv1.Configuration.WatchConfigurations:input_type -> ingressv1.BackendName
	0, // 3: ingressv1.Configuration.GetConfigurations:input_type -> ingressv1.BackendName
	2, // 4: ingressv1.EventService.PublishEvent:input_type -> ingressv1.EventMessage
	1, // 5: ingressv1.Configuration.WatchConfigurations:output_type -> ingressv1.Configurations
	1, // 6: ingressv1.Configuration.GetConfigurations:output_type -> ingressv1.Configurations
	3, // 7: ingressv1.EventService.PublishEvent:output_type -> ingressv1.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_apis_ingress_ingress_proto_init() }
func file_pkg_apis_ingress_ingress_proto_init() {
	if File_pkg_apis_ingress_ingress_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_apis_ingress_ingress_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackendName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_ingress_ingress_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Configurations); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_ingress_ingress_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_ingress_ingress_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_apis_ingress_ingress_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Configurations_FullConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_apis_ingress_ingress_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Configurations_FullconfigOp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_apis_ingress_ingress_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_apis_ingress_ingress_proto_goTypes,
		DependencyIndexes: file_pkg_apis_ingress_ingress_proto_depIdxs,
		MessageInfos:      file_pkg_apis_ingress_ingress_proto_msgTypes,
	}.Build()
	File_pkg_apis_ingress_ingress_proto = out.File
	file_pkg_apis_ingress_ingress_proto_rawDesc = nil
	file_pkg_apis_ingress_ingress_proto_goTypes = nil
	file_pkg_apis_ingress_ingress_proto_depIdxs = nil
}
