timeout: 1200s
options:
  substitution_option: ALLOW_LOOSE
  # Increase machine type for multi-arch builds.
  machineType: E2_HIGHCPU_8
steps:
  - name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20240523-a15ad90fc9
    env:
      - REGISTRY=gcr.io/k8s-staging-ingress-nginx
    entrypoint: bash
    args:
      - -c
      - gcloud auth configure-docker && cd images && make NAME=ext-auth-example-authsvc push
