options:
  # Ignore Prow provided substitutions.
  substitution_option: ALLOW_LOOSE
steps:
- name: gcr.io/cloud-builders/docker
  dir: images
  env:
  - NAME=httpbun
  entrypoint: make
  args:
  - push
