#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

PKG="k8s.io/ingress-nginx"

rm -rf bin/*
mkdir -p bin

ARCH=$ARCH source ./scripts/envs
echo "Building bin/${ARCH}/nginx-ingress-controller"
OUTPUT_BIN="bin/$ARCH/nginx-ingress-controller"
export CGO_ENABLED=0 
GOARCH=$ARCH
go build \
    -a -installsuffix cgo \
    -ldflags="-s -w \
    -X ${PKG}/version.RELEASE=${TAG} \
    -X ${PKG}/version.COMMIT=${COMMIT} \
    -X ${PKG}/version.REPO=${REPO_INFO}" \
    -o ${OUTPUT_BIN} ${PKG}/cmd/nginx
