#!/bin/bash

git config --global user.email "rancher-ci@rancher.com"
git config --global user.name "rancher-ci"

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
    DIRTY="-dirty"
fi

# fetch tag information
git fetch

GIT_COMMIT=${GIT_COMMIT:-$(git rev-parse --short HEAD)}
GIT_TAG=$(git tag -l --contains HEAD | head -n 1)
REPO_INFO=$(git config --get remote.origin.url)

if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
    VERSION=$GIT_TAG
else
    VERSION="${GIT_COMMIT}${DIRTY}"
fi

if [ -z "$ARCH" ]; then
    ARCH=amd64
fi

TAG=${TAG:-$VERSION}

PKG="k8s.io/ingress-nginx"
