controller:
  image:
    repository: ingress-controller/controller
    tag: 1.0.0-dev
    digest: null

  service:
    type: NodePort

    external:
      labels:
        external-dns.alpha.kubernetes.io/hostname: external.example.com

    nodePorts:
      tcp:
        9000: 30090
      udp:
        9001: 30091

portNamePrefix: port

tcp:
  9000: default/test:8080

udp:
  9001: default/test:8080
