controller:
  image:
    repository: ingress-controller/controller
    tag: 1.0.0-dev
    digest: null
  service:
    type: ClusterIP

defaultBackend:
  enabled: true
  extraEnvs:
    - name: IS_METRICS_EXPORT
      value: "false"
    - name: METRICS_PORT
      value: "8081"
  service:
    extraPorts:
      - name: metrics
        port: 8081
        protocol: TCP
        targetPort: 8081
