options:
  # Ignore Prow provided substitutions.
  substitution_option: ALLOW_LOOSE
steps:
  - name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20250116-2a05ea7e3d
    env:
      - REGISTRY=us-central1-docker.pkg.dev/k8s-staging-images/ingress-nginx
    entrypoint: bash
    args:
      - -c
      - gcloud auth configure-docker && cd images && make NAME=cfssl push
