name: Images

on:
  push:
    paths:
    - images/nginx/**

jobs:
  nginx:
    name: NGINX
    runs-on: ubuntu-latest

    steps:
    - name: Show version
      run: docker version
    - name: Show info
      run: docker info
    - name: List builders
      run: docker buildx ls
